version: "3.8"
services: 

  core-service:
    container_name: frontend
    build: ./code/core_service
    image: core-service:latest
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      app_version: 1

  buy_backend:
    container_name: buy_backend
    build: ./code/buy_backend
    image: buy_backend:latest
    ports:
      - target: 5001
        published: 5001
        protocol: tcp

  strat_backend:
    container_name: strat_backend
    build: ./code/strat_backend
    image: strat_backend:latest
    ports:
      - target: 5002
        published: 5002
        protocol: tcp

  round_strength:
    container_name: round_strength
    build: ./code/round_strength
    image: round_strength:latest
    ports:
      - target: 5003
        published: 5003
        protocol: tcp