version: "3.3"
services: 

  core_service:
    # container_name: core_service
    build: ./code/core_service
    image: naailc/core_service:latest
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  
  buy_backend:
    # container_name: buy_backend1
    build: ./code/buy_backend
    image: naailc/buy_backend:latest
    ports:
      - target: 5001
        published: 5001
        protocol: tcp

  strat_backend:
    # container_name: strat_backend
    build: ./code/strat_backend
    image: naailc/strat_backend:latest
    ports:
      - target: 5002
        published: 5002
        protocol: tcp

  round_strength:
    # container_name: round_strength
    build: ./code/round_strength
    image: naailc/round_strength:latest
    ports:
      - target: 5003
        published: 5003
        protocol: tcp