---
  - name: Setup nginx
    become: true
    hosts: nginxmanager
    roles:
      - nginx
  - name: Init docker swarm 
    become: true
    hosts: managers
    roles:
      - docker
      - swarm-init
  - name: Add workers to swarm
    become: true
    hosts: workers
    roles:
      - docker
      - swarm_worker
