- name: setup nginx
  become: true
  hosts: nginx
  roles:
    - nginx

- name: initialize docker swarm
  become: true
  hosts: managers
  roles:
    - swarm_init
    - docker

- name: add workers to swarm 
  hosts: workers
  become: true 
  roles:
    - swarm-worker
    - swarm-worker2
    - docker
